name: mlflow-ci

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          activate-environment: mlflow-env
          python-version: 3.10

      - name: Install mlflow
        run: |
          pip install mlflow==2.9.2

      - name: Run mlflow training
        run: |
          cd Workflow-CI/MLProject
          mlflow run .

      - name: Upload MLflow Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: mlflow-artifacts
          path: Workflow-CI/MLProject/mlruns
