name: mlflow-ci

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: mlflow-env
          python-version: 3.10
          auto-update-conda: true

      - name: Install mlflow + dependencies inside conda env
        shell: bash -l {0}
        run: |
          conda install -c conda-forge mlflow scikit-learn pandas numpy -y

      - name: Run mlflow training
        shell: bash -l {0}
        run: |
          cd Workflow-CI/MLProject
          mlflow run .

      - name: Upload MLflow Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: Workflow-CI/MLProject/mlruns
